const { spawn } = require('child_process');
const path = require('path');
const fs = require('fs');

// AI reviewer max budget — hardcoded, no UI option (per Phase 4.7)
const MAX_BUDGET_USD = 0.50;
const BUDGET_WARNING_USD = 0.40;
const TIMEOUT_MS = 8 * 60 * 1000; // 8 minutes (reviewer patches, doesn't generate)

// ── Stream-JSON message parser ─────────────────────────────────────────────────

function formatStreamMessage(msg) {
  try {
    if (msg.type === 'assistant') {
      const content = msg.message?.content || [];
      for (const block of content) {
        if (block.type === 'text' && block.text?.trim()) {
          const preview = block.text.trim().slice(0, 220).replace(/\n+/g, ' ');
          return `[Reviewer] ${preview}${block.text.length > 220 ? '…' : ''}`;
        }
        if (block.type === 'tool_use') {
          const name = block.name || 'tool';
          const input = block.input || {};
          if (name === 'Bash')                    return `[Bash] ${(input.command || '').slice(0, 120)}`;
          if (name === 'Edit' || name === 'MultiEdit') return `[Edit] ${input.file_path || input.path || '?'}`;
          if (name === 'Write')                   return `[Write] ${input.file_path || '?'}`;
          if (name === 'Read')                    return `[Read] ${input.file_path || input.path || '?'}`;
          return `[${name}] ${JSON.stringify(input).slice(0, 100)}`;
        }
      }
      return null;
    }

    if (msg.type === 'result') {
      const parts = [];
      if (msg.num_turns)   parts.push(`${msg.num_turns} turns`);
      if (msg.cost_usd != null) {
        const cost = msg.cost_usd;
        const costStr = `$${cost.toFixed(4)}`;
        // Budget warning at $0.40
        if (cost >= BUDGET_WARNING_USD) {
          parts.push(`⚠ ${costStr} (approaching $${MAX_BUDGET_USD} limit)`);
        } else {
          parts.push(costStr);
        }
      }
      const status = msg.subtype === 'success' ? '✓ Complete' : `Ended (${msg.subtype})`;
      return `[Reviewer] ${status}${parts.length ? ` · ${parts.join(' · ')}` : ''}`;
    }
  } catch (_) { /* ignore parse errors */ }
  return null;
}

// ── Build the reviewer mission prompt ─────────────────────────────────────────

function buildReviewerPrompt(briefContext) {
  const {
    brandName, tagline, industry, aesthetic, siteType,
    callToAction, componentList, mappedComponents, unmappedComponents, contentOverrides, pages,
  } = briefContext;

  const hasUnmapped = unmappedComponents && unmappedComponents.length > 0;
  const hasTsErrors = briefContext._tsErrors && briefContext._tsErrors.trim();

  // Read REVIEWER_BRIEF.md if it exists in the project (provides richer context)
  const reviewerBriefNote = `Read REVIEWER_BRIEF.md in the project root for full context and fix checklist.`;

  const lines = [
    `You are reviewing a React/Vite/TypeScript project generated by a template engine.`,
    `DO NOT rewrite correct files. Only fix what is broken or missing.`,
    ``,
    reviewerBriefNote,
    ``,
    `PROJECT SUMMARY:`,
    `  Brand: ${brandName}${tagline ? ` — "${tagline}"` : ''}`,
    `  Industry: ${industry || 'General'}`,
    `  Aesthetic: ${aesthetic} | Site type: ${siteType}`,
    `  Primary CTA: "${callToAction}"`,
    `  Pages: ${pages && pages.length > 0 ? pages.map(p => p.name || p.label).join(', ') : 'Single page'}`,
    ``,
    `PRIORITY FIX ORDER:`,
    hasUnmapped
      ? `1. UNMAPPED COMPONENTS — these rendered as placeholder divs, fix them now:\n   ${unmappedComponents.join(', ')}\n   Find each in src/components/, read the source, replace placeholder div with real usage.`
      : `1. No unmapped components — skip this step.`,
    hasTsErrors
      ? `2. TYPESCRIPT ERRORS — fix every error from this output:\n${(briefContext._tsErrors || '').slice(0, 2000)}`
      : `2. TypeScript was clean — skip this step.`,
    `3. CONTENT — ensure brand-specific copy throughout:`,
    `   - Replace any "Brand Studio" / generic fallbacks with: "${brandName}"`,
    `   - Tagline should appear in hero: "${tagline || brandName}"`,
    `   - Primary button CTA: "${callToAction}"`,
    Object.keys(contentOverrides || {}).length > 0
      ? `   - Content overrides from AI enhancer:\n${JSON.stringify(contentOverrides, null, 2)}`
      : '',
    `4. AESTHETIC — every section must follow ${aesthetic} style rules from index.css`,
    `5. Z-INDEX — verify: backgrounds z:0, page content z:1+, nav z:100+`,
    ``,
    `HARD RULES:`,
    `- DO NOT touch files that have no issues`,
    `- DO NOT add new npm packages (all are already installed)`,
    `- DO NOT add placeholder comments (// TODO, /* FILL */, etc.)`,
    `- Use CSS variables: --color-bg, --color-text, --color-accent, --color-primary`,
    `- All components are in src/components/{category}/{name}/{name}.tsx`,
    ``,
    `When all fixes are done, output: DONE`,
  ].filter(l => l !== undefined).join('\n');

  return lines;
}

// ── Main export ───────────────────────────────────────────────────────────────

/**
 * reviewCode({ projectPath, tsErrors, briefContext, onProgress })
 *
 * Runs Claude Code as a targeted reviewer to patch a deterministically generated project.
 * Budget: $0.50 max (hardcoded). Timeout: 8 minutes.
 *
 * @param {object} params
 * @param {string} params.projectPath   - Absolute path to the generated project on disk
 * @param {string} params.tsErrors      - Output from `npx tsc --noEmit` (may be empty)
 * @param {object} params.briefContext  - Metadata about the project
 * @param {function} params.onProgress  - Progress callback (string → void)
 */
async function reviewCode({ projectPath, tsErrors, briefContext, onProgress }, _attempt = 0) {
  const notify = (msg) => { if (onProgress) onProgress(msg); };

  // Attach tsErrors into briefContext so buildReviewerPrompt can use them
  const ctx = { ...briefContext, _tsErrors: tsErrors };
  const prompt = buildReviewerPrompt(ctx);

  return new Promise((resolve, reject) => {
    let saw429 = false;
    const isWin = process.platform === 'win32';

    // Escape prompt for shell: wrap in double quotes, escape inner double quotes
    const safePrompt = prompt.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');

    const cmd = [
      'npx @anthropic-ai/claude-code',
      '--print',
      '--verbose',
      '--dangerously-skip-permissions',
      '--output-format stream-json',
      '--model claude-sonnet-4-6',
      `--max-turns 20`,
      `--max-budget-usd ${MAX_BUDGET_USD}`,
      `"${safePrompt}"`,
    ].join(' ');

    const child = spawn(cmd, [], {
      cwd: path.resolve(projectPath),
      shell: true,
      windowsHide: true,
      env: { ...process.env },
    });

    const timeoutHandle = setTimeout(() => {
      notify('[Reviewer] ⏱ Timed out after 8 minutes. Terminating...');
      if (isWin) {
        try { require('child_process').execSync(`taskkill /pid ${child.pid} /T /F`, { stdio: 'ignore' }); } catch (_) {}
      } else {
        child.kill('SIGTERM');
      }
      reject(new Error('[Reviewer] Timed out.'));
    }, TIMEOUT_MS);

    let stdoutBuf = '';
    child.stdout.on('data', (data) => {
      stdoutBuf += data.toString();
      const lines = stdoutBuf.split('\n');
      stdoutBuf = lines.pop(); // keep incomplete last line in buffer

      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed) continue;
        try {
          const msg = JSON.parse(trimmed);
          const ui = formatStreamMessage(msg);
          if (ui) notify(ui);
        } catch (_) {
          // Plain text output — log if meaningful
          if (!trimmed.startsWith('npm warn') && !trimmed.includes('added ') && trimmed.length > 2) {
            notify(trimmed);
          }
        }
      }
    });

    let stderrBuf = '';
    child.stderr.on('data', (data) => {
      stderrBuf += data.toString();
      const lines = stderrBuf.split('\n');
      stderrBuf = lines.pop();
      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('npm warn')) continue;
        if (trimmed.includes('429') || trimmed.toLowerCase().includes('rate limit')) saw429 = true;
        notify(`[stderr] ${trimmed}`);
      }
    });

    child.on('error', (err) => {
      clearTimeout(timeoutHandle);
      reject(new Error(`[Reviewer] Failed to start: ${err.message}`));
    });

    child.on('close', (code) => {
      clearTimeout(timeoutHandle);
      if (code === 0 || code === null) {
        notify('[Reviewer] Review complete.');
        resolve();
      } else if (saw429 && _attempt < 1) {
        notify(`[Reviewer] Rate limit hit — retrying in 65s...`);
        setTimeout(() => {
          reviewCode({ projectPath, tsErrors, briefContext, onProgress }, _attempt + 1)
            .then(resolve).catch(reject);
        }, 65000);
      } else {
        reject(new Error(`[Reviewer] Exited with code ${code}.`));
      }
    });
  });
}

module.exports = { reviewCode };
