/**
 * reviewer-brief.cjs
 * Builds and writes REVIEWER_BRIEF.md — the mission document read by the AI
 * reviewer before it patches the generated project.
 */

const path = require('path');
const fs   = require('fs/promises');
const { isComponentMapped, getMappedNames } = require('../shared/component-mapper.cjs');

/**
 * Builds the plain-object context that feeds both REVIEWER_BRIEF.md and
 * the `reviewCode` call options.
 */
function buildBriefContext({ clientBrief, content, styleDirection, selectedComponents, tsErrors, pages, enhancedPrompt }) {
  return {
    brandName:        clientBrief.brandName || content.brandName || 'Unknown Brand',
    tagline:          clientBrief.tagline || '',
    industry:         clientBrief.industry || '',
    aesthetic:        styleDirection.aesthetics?.[0] || 'Minimal',
    siteType:         styleDirection.siteType || 'Landing',
    callToAction:     clientBrief.callToAction || 'Get Started',
    components:       selectedComponents.map(c => ({ name: c.name, category: c.category })),
    pages,
    contentOverrides: enhancedPrompt?.contentOverrides || {},
  };
}

/**
 * Writes REVIEWER_BRIEF.md to `projectPath`.
 * Lists mapped vs. unmapped components, TS errors, and priority fix order so
 * the AI reviewer has a single source of truth to work from.
 */
async function writeReviewerBrief(projectPath, briefContext, tsErrors) {
  const compList  = briefContext.components || [];
  const mapped    = compList.filter(c => isComponentMapped(c.name)).map(c => c.name);
  const unmapped  = compList.map(c => c.name).filter(n => !mapped.includes(n));

  const sections = [
    `# REVIEWER_BRIEF.md`,
    `_Generated by BitForge — this file is your mission for the AI reviewer._`,
    ``,
    `## Project Info`,
    `| Field | Value |`,
    `|---|---|`,
    `| Brand | ${briefContext.brandName} |`,
    `| Tagline | ${briefContext.tagline || '—'} |`,
    `| Industry | ${briefContext.industry || '—'} |`,
    `| Aesthetic | ${briefContext.aesthetic} |`,
    `| Site Type | ${briefContext.siteType} |`,
    `| CTA | ${briefContext.callToAction} |`,
    ``,
    `## Components`,
    `### Mapped (template-generated, should be working):`,
    mapped.length > 0 ? mapped.map(n => `- ✓ ${n}`).join('\n') : '- (none)',
    ``,
    `### Unmapped (rendered as placeholder divs — YOU MUST FIX THESE):`,
    unmapped.length > 0
      ? unmapped.map(n => `- ✗ ${n} → find it in src/components/, implement real usage`).join('\n')
      : '- (all components mapped, nothing to fix here)',
    ``,
    `## TypeScript Errors`,
    tsErrors
      ? `\`\`\`\n${tsErrors.slice(0, 3000)}\n\`\`\``
      : '✓ No TypeScript errors — tsc was clean.',
    ``,
    `## Priority Fix Order`,
    `1. **Unmapped components** (listed above) — replace placeholder divs with real component usage`,
    `2. **TypeScript errors** (listed above) — fix all type errors`,
    `3. **Content** — replace any generic text with brand-specific copy:`,
    `   - Brand name: "${briefContext.brandName}"`,
    `   - Tagline: "${briefContext.tagline || 'Use brand voice'}"`,
    `   - CTA: "${briefContext.callToAction}"`,
    `4. **Aesthetic consistency** — every section must follow ${briefContext.aesthetic} style rules`,
    `5. **Z-index** — backgrounds: z:0, content: z:10+, nav: z:100+`,
    ``,
    `## Rules`,
    `- DO NOT rewrite files that have no issues`,
    `- DO NOT add new dependencies — all packages are already installed`,
    `- DO NOT add placeholder comments or TODO comments`,
    `- Use CSS variables from \`:root\` (--color-bg, --color-text, --color-accent, --color-primary)`,
    `- **Text contrast**: NEVER set text the same or similar color as its background. Every \`<p>\`, \`<h1>\`–\`<h6>\`, \`<span>\`, \`<li>\` must have \`color: 'var(--color-text)'\` (or a contrasting explicit color). If a section has a dark surface background, use a light text color explicitly.`,
    `- **All text must be readable**: if in doubt, add \`color: 'var(--color-text)'\` explicitly — never rely on inheritance alone when background colors change between sections.`,
    `- When finished with all fixes, output: DONE`,
    ``,
    `## Brief Context JSON`,
    `\`\`\`json`,
    JSON.stringify(briefContext, null, 2),
    `\`\`\``,
  ];

  await fs.writeFile(path.join(projectPath, 'REVIEWER_BRIEF.md'), sections.join('\n'), 'utf-8');
}

module.exports = { buildBriefContext, writeReviewerBrief };
