/**
 * brief-writer.cjs
 * Writes Brief.md to the generated project root.
 *
 * Called after app-builder completes.  If Brief.md was not already written by
 * app-builder (or was written but is missing), this creates a full fallback
 * version from the available options so the project always ships with one.
 */

const path = require('path');
const fs   = require('fs/promises');

async function ensureBriefFile({
  fullPath,
  selectedComponents = [],
  styleDirection = {},
  designRules = {},
  clientBrief = {},
  pages = [],
  presetName = '',
  packageManager = 'npm',
  onProgress = () => {},
}) {
  const briefPath = path.join(fullPath, 'Brief.md');
  try {
    await fs.access(briefPath);
    return; // Already exists — nothing to do
  } catch (_) { /* Missing — create fallback below */ }

  const now    = new Date();
  const nowIso = now.toISOString();
  const date   = nowIso.slice(0, 10);

  // ── Component inventory ───────────────────────────────────────────────────
  const byCategory = {};
  for (const c of selectedComponents) {
    const cat = c.category || 'Other';
    if (!byCategory[cat]) byCategory[cat] = [];
    byCategory[cat].push(c.name);
  }
  const totalComponents = selectedComponents.length;
  const totalPages = Array.isArray(pages) && pages.length > 0 ? pages.length : 1;

  const componentSection = Object.entries(byCategory)
    .map(([cat, names]) => `### ${cat}\n${names.map(n => `- ${n}`).join('\n')}`)
    .join('\n\n');

  const categoryRows = Object.entries(byCategory)
    .map(([cat, names]) => `| ${cat} | ${names.length} |`)
    .join('\n') || '| None | 0 |';

  // ── Page table ────────────────────────────────────────────────────────────
  const pageRows = (Array.isArray(pages) && pages.length > 0 ? pages : [{ title: 'Home', type: 'home' }])
    .map((p, i) => {
      const title = p.title || p.name || `Page ${i + 1}`;
      const type  = p.type || 'custom';
      const route = type === 'home'    ? '/'
                  : type === 'about'   ? '/about'
                  : type === 'services'? '/services'
                  : type === 'contact' ? '/contact'
                  : '/' + String(title).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
      return `| ${i + 1} | ${title} | ${type} | \`${route}\` |`;
    })
    .join('\n');

  // ── Design token tables ───────────────────────────────────────────────────
  const colors = Array.isArray(designRules.colors) ? designRules.colors : [];
  const colorRows = colors.length > 0
    ? colors.map(c => {
        const value  = c.value || c.hex || '—';
        const swatch = typeof value === 'string' && value.startsWith('#')
          ? `<span style="display:inline-block;width:12px;height:12px;border-radius:999px;background:${value};border:1px solid rgba(255,255,255,.25);vertical-align:middle;"></span>`
          : '—';
        return `| ${c.role || 'auto'} | ${value} | ${swatch} |`;
      }).join('\n')
    : '| auto | — | — |';

  const fonts = Array.isArray(designRules.fonts) ? designRules.fonts : [];
  const fontRows = fonts.length > 0
    ? fonts.map(f => `| ${f.role || 'auto'} | ${f.family || f.value || '—'} | ${f.weight || 'default'} |`).join('\n')
    : '| auto | Default system | default |';

  // ── Assemble markdown ─────────────────────────────────────────────────────
  const lines = [
    `# Project Brief: ${clientBrief.brandName || 'Project'}`,
    ``,
    `> Generated by BitForge`,
    `> Date: ${date}`,
    `> Timestamp: ${nowIso}`,
    `> Source: Fallback brief writer (auto-recovered)`,
    presetName ? `> Preset: ${presetName}` : '',
    ``,
    `## Snapshot`,
    ``,
    `| Key | Value |`,
    `| --- | --- |`,
    `| Brand | ${clientBrief.brandName || 'Project'} |`,
    `| Tagline | ${clientBrief.tagline || '—'} |`,
    `| Site Type | ${styleDirection.siteType || 'Landing'} |`,
    `| Aesthetic | ${(styleDirection.aesthetics || [])[0] || 'Minimal'} |`,
    `| Color Strategy | ${styleDirection.colorStrategy || '—'} |`,
    `| Industry | ${clientBrief.industry || '—'} |`,
    `| Audience | ${clientBrief.targetAudience || '—'} |`,
    `| CTA | ${clientBrief.callToAction || '—'} |`,
    `| Components | ${totalComponents} |`,
    `| Pages | ${totalPages} |`,
    `| Package Manager | ${packageManager} |`,
    ``,
    `---`,
    ``,
    `## Client Brief Inputs`,
    ``,
    `| Field | Value |`,
    `| --- | --- |`,
    `| Description | ${clientBrief.description || '—'} |`,
    `| Tone | ${clientBrief.tone || '—'} |`,
    `| Personality | ${clientBrief.personality || '—'} |`,
    `| USP | ${clientBrief.usp || '—'} |`,
    ``,
    `---`,
    ``,
    `## Forge Style Direction`,
    ``,
    `| Setting | Value |`,
    `| --- | --- |`,
    `| Aesthetics | ${(styleDirection.aesthetics || []).join(', ') || '—'} |`,
    `| Site Type | ${styleDirection.siteType || '—'} |`,
    `| Color Strategy | ${styleDirection.colorStrategy || '—'} |`,
    `| Typography Intensity | ${styleDirection.typographyIntensity || '—'} |`,
    `| Visual Effects | ${(styleDirection.visualEffects || []).join(', ') || '—'} |`,
    `| Audience Hint | ${styleDirection.audience || '—'} |`,
    ``,
    `---`,
    ``,
    `## Configuration Panel Rules`,
    ``,
    `- Optimization Target: ${designRules?.sizes?.optimizationTarget || 'adaptive'}`,
    `- Spacing Scale: ${designRules?.sizes?.spacingScale || '—'}`,
    `- Border Radius: ${designRules?.sizes?.borderRadius || '—'}`,
    ``,
    `### Colors`,
    ``,
    `| Role | Value | Swatch |`,
    `| --- | --- | --- |`,
    colorRows,
    ``,
    `### Fonts`,
    ``,
    `| Role | Family | Weight |`,
    `| --- | --- | --- |`,
    fontRows,
    ``,
    `---`,
    ``,
    `## Component Inventory`,
    ``,
    `| Category | Count |`,
    `| --- | ---: |`,
    categoryRows,
    ``,
    `## Selected Components`,
    ``,
    componentSection || '- None',
    ``,
    `---`,
    ``,
    `## Pages`,
    ``,
    `| # | Name | Type | Route |`,
    `| ---: | --- | --- | --- |`,
    pageRows,
    ``,
    `---`,
    ``,
    `## Quick Start`,
    ``,
    `\`\`\`bash`,
    `${packageManager} install`,
    `${packageManager} run dev`,
    `\`\`\``,
    ``,
  ].join('\n');

  await fs.writeFile(briefPath, lines, 'utf-8');
  onProgress('Brief.md was missing and has been re-created with full detail.');
}

module.exports = { ensureBriefFile };
