import { exec } from 'child_process';
import { promisify } from 'util';
import path from 'path';
import fs from 'fs/promises';

const execAsync = promisify(exec);

export interface GenerateViteReactOptions {
  targetDir: string;
  projectName: string;
  componentCategory: string;
  componentName: string;
  componentFiles: { name: string, content: string }[];
  usageCode: string;
  packageManager: 'npm' | 'pnpm' | 'yarn' | 'bun';
  installData: any;
}

export async function generateViteReact(options: GenerateViteReactOptions) {
  const { targetDir, projectName, componentCategory, componentName, componentFiles, usageCode, packageManager, installData } = options;

  console.log(`[DemoCLI] Starting generation of Vite + React project at ${targetDir}`);
  const parentDir = path.dirname(targetDir);

  // 1. Run Vite Scaffold
  const createCmd = packageManager === 'npm' ? 'npm create vite@latest' : `${packageManager} create vite`;
  console.log(`[DemoCLI] Running: ${createCmd} ${projectName} -- --template react-ts`);
  
  // Note: Vite's CLI sometimes prompts if not careful, but `-- --template react-ts` usually bypasses it for NPM.
  // For safety across managers:
  let scaffoldCmd = '';
  if (packageManager === 'npm') scaffoldCmd = `npm create vite@latest ${projectName} -- --template react-ts`;
  if (packageManager === 'pnpm') scaffoldCmd = `pnpm create vite ${projectName} --template react-ts`;
  if (packageManager === 'yarn') scaffoldCmd = `yarn create vite ${projectName} --template react-ts`;
  if (packageManager === 'bun') scaffoldCmd = `bun create vite ${projectName} --template react-ts`;

  await execAsync(scaffoldCmd, { cwd: parentDir });

  // 2. Install reactbits required dependencies
  const installDeps = async (cmd: string) => {
    if (!cmd) return;
    console.log(`[DemoCLI] Installing dependencies: ${cmd}`);
    try {
      await execAsync(cmd, { cwd: targetDir });
    } catch (e) {
      console.error(`[DemoCLI] Warning: Failed to run dependency install command: ${cmd}`, e);
    }
  };

  if (installData?.cli?.[packageManager]) {
    await installDeps(installData.cli[packageManager]);
  } else if (installData?.manual?.[packageManager]) {
    // If no CLI command, try to extract packages from manual command
    const manualLine = installData.manual[packageManager];
    const match = manualLine.match(/(?:add|install)\s+([^.]+)/);
    if (match && match[1]) {
      const pkgNames = match[1].trim().split(/\s+/).filter((p: string) => p && !p.startsWith('-'));
      if (pkgNames.length > 0) {
        const installCmd = packageManager === 'npm' ? `npm install ${pkgNames.join(' ')}` : `${packageManager} add ${pkgNames.join(' ')}`;
        await installDeps(installCmd);
      }
    }
  }

  // Also do a blanket install for the Vite template
  console.log(`[DemoCLI] Installing base Vite dependencies...`);
  await execAsync(`${packageManager} install`, { cwd: targetDir });

  // 3. Inject Component Files
  const componentDirPath = path.join(targetDir, 'src', 'components', componentCategory, componentName);
  await fs.mkdir(componentDirPath, { recursive: true });

  for (const file of componentFiles) {
    const filePath = path.join(componentDirPath, file.name);
    await fs.writeFile(filePath, file.content, 'utf-8');
  }

  // 4. Overwrite App.tsx with the Usage Example
  // We'll replace the default App.tsx from Vite with a wrapper that renders the usageCode.
  const appTsxPath = path.join(targetDir, 'src', 'App.tsx');
  
  // We need to adjust imports in the usageCode to point to the correct local path since 
  // they usually look like `import Component from './Component'`. 
  // This can get tricky if imports are wrong, but we'll drop the usageCode exactly as-is into App.tsx
  // and assume the user's setup usage blocks are relatively self-contained, or we modify them.
  // A safer bet: The ReactBits usage code often defines `App()`. We just dump it.
  
  // Quick fix: ReactBits usage docs usually assume `./ComponentName`. 
  // We placed it at `src/components/Category/Name/Name.tsx`.
  // We will do a generic regex replace for `./${componentName}` -> `./components/${componentCategory}/${componentName}/${componentName}`
  
  let modifiedUsageCode = usageCode.replace(
    new RegExp(`from\\s+['"]\\.\\/${componentName}['"]`, 'g'),
    `from './components/${componentCategory}/${componentName}/${componentName}'`
  );

  await fs.writeFile(appTsxPath, modifiedUsageCode, 'utf-8');

  const appCssPath = path.join(targetDir, 'src', 'App.css');
  await fs.writeFile(appCssPath, '/* Generated by ReactBits Explorer */\n', 'utf-8');

  // 6. Create dev.bat for Windows Execution Policy Bypass
  const devBatPath = path.join(targetDir, 'dev.bat');
  const devBatContent = `@echo off\necho Starting ReactBits Playground...\nPowerShell -ExecutionPolicy Bypass -Command "${packageManager} run dev"\npause`;
  await fs.writeFile(devBatPath, devBatContent, 'utf-8');

  console.log(`[DemoCLI] Finished setting up target project at ${targetDir}`);
  return true;
}
