import { exec } from 'child_process';
import { promisify } from 'util';
import path from 'path';
import fs from 'fs/promises';

const execAsync = promisify(exec);

export interface GenerateViteReactOptions {
  targetDir: string;
  projectName: string;
  componentCategory: string;
  componentName: string;
  componentFiles: { name: string, content: string }[];
  usageCode: string;
  packageManager: 'npm' | 'pnpm' | 'yarn' | 'bun';
  installData: any;
}

export async function generateViteReact(options: GenerateViteReactOptions) {
  const { targetDir, projectName, componentCategory, componentName, componentFiles, usageCode, packageManager, installData } = options;

  console.log(`[DemoCLI] Starting generation of Vite + React project at ${targetDir}`);
  const parentDir = path.dirname(targetDir);

  // 1. Run Vite Scaffold
  const createCmd = packageManager === 'npm' ? 'npm create vite@latest' : `${packageManager} create vite`;
  console.log(`[DemoCLI] Running: ${createCmd} ${projectName} -- --template react-ts`);
  
  // Note: Vite's CLI sometimes prompts if not careful, but `-- --template react-ts` usually bypasses it for NPM.
  // For safety across managers:
  let scaffoldCmd = '';
  if (packageManager === 'npm') scaffoldCmd = `npm create vite@latest ${projectName} -- --template react-ts`;
  if (packageManager === 'pnpm') scaffoldCmd = `pnpm create vite ${projectName} --template react-ts`;
  if (packageManager === 'yarn') scaffoldCmd = `yarn create vite ${projectName} --template react-ts`;
  if (packageManager === 'bun') scaffoldCmd = `bun create vite ${projectName} --template react-ts`;

  await execAsync(scaffoldCmd, { cwd: parentDir });

  // 2. Install reactbits required dependencies
  // Parsed install data usually holds the required commands, e.g., "npm i framer-motion"
  let depsCommand = "";
  if (installData?.cli && installData.cli[packageManager]) {
    // The installData.cli string might be like: "npm i framer-motion clsx tailwind-merge"
    // We just run what they gave us or extract the package names.
    // If it's a full command, we execute it directly in the new folder.
    depsCommand = installData.cli[packageManager];
    
    // Quick cleanup: ReactBits usage often includes the 'react-bits' package or similar. 
    // If the CLI instruction says `npm i ...`, we run it.
    if (depsCommand) {
      console.log(`[DemoCLI] Installing component dependencies: ${depsCommand}`);
      try {
        await execAsync(depsCommand, { cwd: targetDir });
      } catch (e) {
        console.error(`[DemoCLI] Warning: Failed to run dependency install command: ${depsCommand}`, e);
      }
    }
  }

  // Also do a blanket install for the Vite template
  console.log(`[DemoCLI] Installing base Vite dependencies...`);
  await execAsync(`${packageManager} install`, { cwd: targetDir });

  // 3. Inject Component Files
  const componentDirPath = path.join(targetDir, 'src', 'components', componentCategory, componentName);
  await fs.mkdir(componentDirPath, { recursive: true });

  for (const file of componentFiles) {
    const filePath = path.join(componentDirPath, file.name);
    await fs.writeFile(filePath, file.content, 'utf-8');
  }

  // 4. Overwrite App.tsx with the Usage Example
  // We'll replace the default App.tsx from Vite with a wrapper that renders the usageCode.
  const appTsxPath = path.join(targetDir, 'src', 'App.tsx');
  
  // We need to adjust imports in the usageCode to point to the correct local path since 
  // they usually look like `import Component from './Component'`. 
  // This can get tricky if imports are wrong, but we'll drop the usageCode exactly as-is into App.tsx
  // and assume the user's setup usage blocks are relatively self-contained, or we modify them.
  // A safer bet: The ReactBits usage code often defines `App()`. We just dump it.
  
  // Quick fix: ReactBits usage docs usually assume `./ComponentName`. 
  // We placed it at `src/components/Category/Name/Name.tsx`.
  // We will do a generic regex replace for `./${componentName}` -> `./components/${componentCategory}/${componentName}/${componentName}`
  
  let modifiedUsageCode = usageCode.replace(
    new RegExp(`from\\s+['"]\\.\\/${componentName}['"]`, 'g'),
    `from './components/${componentCategory}/${componentName}/${componentName}'`
  );

  await fs.writeFile(appTsxPath, modifiedUsageCode, 'utf-8');

  // 5. Clean up Vite boilerplate CSS (optional but makes it look like the demo)
  const appCssPath = path.join(targetDir, 'src', 'App.css');
  await fs.writeFile(appCssPath, '/* Generated by ReactBits Explorer */\n', 'utf-8');

  console.log(`[DemoCLI] Finished setting up target project at ${targetDir}`);
  return true;
}
